openapi: 3.0.3
info:
  title: STD24001
  description: "This is a specification of STD24001"
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /booking:
    get:
      summary: Récupérer la liste des réservations
      description: Permet de récupérer une liste de réservations sauvegardée dans la mémoire vive
      responses:
        '200':
          description: Liste des réservations récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Créer une nouvelle réservation
      description: Permet de créer une nouvelle réservation suivant les caractéristiques mentionnées et retourne la liste de réservations créées ou modifiées
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '200':
          description: Réservation créée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '400':
          description: Données invalides ou chambre déjà réservée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Booking:
      allOf:
        - $ref: '#/components/schemas/Customer'
        - $ref: '#/components/schemas/Room'
        - type: object
          properties:
            reservationDate:
              type: string
              format: date
              example: "05/09/2025"
              description: Date de la réservation au format DD/MM/YYYY
          required:
            - reservationDate

    BookingRequest:
      allOf:
        - $ref: '#/components/schemas/Customer'
        - $ref: '#/components/schemas/Room'
        - type: object
          properties:
            reservationDate:
              type: string
              format: date
              example: "05/09/2025"
              description: Date de la réservation au format DD/MM/YYYY
          required:
            - reservationDate

    Customer:
      type: object
      properties:
        customerName:
          type: string
          description: Nom du client
          example: "Jean Dupont"
        phoneNumber:
          type: string
          description: Numéro de téléphone du client
          example: "+33123456789"
        email:
          type: string
          format: email
          description: Adresse email du client
          example: "jean.dupont@email.com"
      required:
        - customerName
        - phoneNumber
        - email

    Room:
      type: object
      properties:
        roomNumber:
          type: integer
          minimum: 1
          maximum: 9
          description: Numéro de chambre (entre 1 et 9 uniquement)
          example: 5
        roomDescription:
          type: string
          description: Description de la chambre
          example: "Chambre double avec vue sur mer"
      required:
        - roomNumber
        - roomDescription

    Error:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur
          example: "La chambre n'est plus disponible pour cette date"
        code:
          type: integer
          description: Code d'erreur
          example: 400
      required:
        - message
        - code
