openapi: 3.0.3
info:
  title: Booking API
  version: 1.0.0
  description: API de gestion des réservations
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /booking:
    get:
      summary: Récupérer la liste des réservations
      description: Permet de récupérer une liste de réservations sauvegardée dans la mémoire vive
      responses:
        '200':
          description: Liste des réservations récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Créer une nouvelle réservation
      description: Permet de créer une nouvelle réservation suivant les caractéristiques mentionnées et retourne la liste de réservations créées ou modifiées
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '201':
          description: Réservation créée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
        '400':
          description: Données invalides ou chambre déjà réservée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Booking:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Identifiant unique de la réservation
          example: "123e4567-e89b-12d3-a456-426614174000"
        customer:
          $ref: '#/components/schemas/Customer'
        room:
          $ref: '#/components/schemas/Room'
        reservationDate:
          type: string
          format: date
          example: "2025-09-05"
          description: Date de la réservation au format YYYY-MM-DD
      required:
        - id
        - customer
        - room
        - reservationDate

    BookingRequest:
      type: object
      properties:
        customer:
          $ref: '#/components/schemas/Customer'
        room:
          $ref: '#/components/schemas/Room'
        reservationDate:
          type: string
          format: date
          example: "2025-09-05"
          description: Date de la réservation au format YYYY-MM-DD
      required:
        - customer
        - room
        - reservationDate

    Customer:
      type: object
      properties:
        customerName:
          type: string
          description: Nom du client
          example: "Jean Dupont"
        phoneNumber:
          type: string
          description: Numéro de téléphone du client
          example: "+33123456789"
        email:
          type: string
          format: email
          description: Adresse email du client
          example: "jean.dupont@email.com"
      required:
        - customerName
        - phoneNumber
        - email

    Room:
      type: object
      properties:
        roomNumber:
          type: integer
          minimum: 1
          maximum: 9
          description: Numéro de chambre (entre 1 et 9 uniquement)
          example: 5
        roomDescription:
          type: string
          description: Description de la chambre
          example: "Chambre double avec vue sur mer"
      required:
        - roomNumber
        - roomDescription

    Error:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur
          example: "La chambre n'est plus disponible pour cette date"
        code:
          type: integer
          description: Code d'erreur
          example: 400
        details:
          type: string
          description: Détails supplémentaires sur l'erreur
          example: "Chambre 5 déjà réservée pour le 2025-09-05"
      required:
        - message
        - code
